language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/raku-test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libgtk-3-dev

script: docker run -t --user root -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test

